// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCFDZ6Llq4G_2aYRNAdCT5oJuVDpSDeg',
    appId: '1:535065746745:web:92d8349394fbd622d65ce8',
    messagingSenderId: '535065746745',
    projectId: 'opportunity-hub-dacd0',
    authDomain: 'opportunity-hub-dacd0.firebaseapp.com',
    storageBucket: 'opportunity-hub-dacd0.firebasestorage.app',
    measurementId: 'G-BNL33JKVKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQUz_JEAPWkjGFTPRvrCUBr7KaYjqXYs',
    appId: '1:535065746745:android:514ce9445753188dd65ce8',
    messagingSenderId: '535065746745',
    projectId: 'opportunity-hub-dacd0',
    storageBucket: 'opportunity-hub-dacd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAThXNpu3WxCexwFhUj6pD8vaOoYuCe4sA',
    appId: '1:535065746745:ios:7a04beb62f2bd6bfd65ce8',
    messagingSenderId: '535065746745',
    projectId: 'opportunity-hub-dacd0',
    storageBucket: 'opportunity-hub-dacd0.firebasestorage.app',
    iosBundleId: 'com.example.creovate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAThXNpu3WxCexwFhUj6pD8vaOoYuCe4sA',
    appId: '1:535065746745:ios:7a04beb62f2bd6bfd65ce8',
    messagingSenderId: '535065746745',
    projectId: 'opportunity-hub-dacd0',
    storageBucket: 'opportunity-hub-dacd0.firebasestorage.app',
    iosBundleId: 'com.example.creovate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOCFDZ6Llq4G_2aYRNAdCT5oJuVDpSDeg',
    appId: '1:535065746745:web:3ae8b0f93e2dc607d65ce8',
    messagingSenderId: '535065746745',
    projectId: 'opportunity-hub-dacd0',
    authDomain: 'opportunity-hub-dacd0.firebaseapp.com',
    storageBucket: 'opportunity-hub-dacd0.firebasestorage.app',
    measurementId: 'G-9WM8MG02KF',
  );
}
